### ISSUE TITLE
Is there any source code?

### ISSUE THREAD

**Issue by LiuHao-THU** [ArztSamuel/Applying_EANNs#1]
it's really a fancy algorithm, I really like  it

**Comment by ArztSamuel** [comment]
That is the entire purpose of this repository. It consists of the source code of the project.
I assume what you are looking for is the C# scripts that are responsible for the logic of the simulation. All scripts can be found in the [UnityProject/Assets/Scripts/](https://github.com/ArztSamuel/Applying_EANNs/tree/master/UnityProject/Assets/Scripts) folder.

**Comment by LiuHao-THU** [comment]
thanks for the reply, I never used c#, so I did not recognize the source code.  and it's a litter hard for me to understand, can you recommend some tutorial or paper for study this algorithm, I really like this code...

**Comment by ArztSamuel** [comment]
As far as papers are concerned I recommend Jurgen Schmidhuber's Deep Learning Overview and Darrell Whitley's "A Genetic Algorithm Tutorial".
There are also a lot of courses about machine/deep learning on all popular online-course sites.

**Comment by LiuHao-THU** [comment]
thanks for the reply, I will check the tutorial.
